import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
    en: {
        lang: "en",
        welcome: "Welcome",
        mealList: "Meal List",
        mustFaculty: "Faculty (Mandatory)",
        editProfile: "Edit Profile",
        canEdit: "You can edit.",
        username: "Username",
        urUsername: "Write username",
        mustDepartment: "Department (Mandatory)",
        cancel: "Cancel",
        save: "Save",
        faculty: "Faculty",
        department: "Department",
        mood: "Mood",
        edit: "Edit",
        calendarString1: "syllabus couldn't found.",
        calendarString2: "It will be added as soon as possible.",
        departmentSite1: "website couldn't found.",
        fillTheGaps: "Fill the gaps.",
        start: "Start",
        onboarding1Text: "AYBU has a mobile app now.",
        onboarding2Text: "Learn what’s in the menu in a moment, and show your feelings about it.",
        onboarding3Text: "Get a chance to express your opinions about menu.",
        onboarding4Text: "Know the best and worst foods in the menu.",
        onboarding1Title: "Hey",
        onboarding2Title: "Meal List",
        onboarding3Title: "Comment",
        onboarding4Title: "Trend",
        noComment1: "There are no comments.",
        noComment2: "Write the first one!",
        error: "Error",
        success: "Success",
        registeredSuccess: "Logging in..",
        cantLogin: "Failed to login. Please try again",
        cantRegister: "Bu kullanıcı adı daha önce alınmış",
        writeComment: "Write comment...",
        commentCouldntSend: "Failed to fetch comments",
        anErrorOccured: "An error has occurred",
        mealList: 'Meal List',
        successUpdate: "Your profile has been updated.",
        trends: "TRENDS",
        mostFavoriteDays: "Favorite Days",
        mostUnfavoriteDays: "Unfavorite Days",
        mostCommentDays: "Most Commented Days",
        today: "Today",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
        sunday: "Sunday",
        examSchedule: "Exam Schedule",
        syllabus: "Syllabus",
        helpAYBU: "You could help add this document to Aybü Mobil by sending it in pdf format by e-mail.",
        clickToSendMail: "Click to send mail.",
        sharedWithFriends: "Share with your friends!",
        skip: "Skip",
        selectDepartment: "Select Department",
        selectFaculty: "Select Faculty",
        downloadLinks: "AYBÜ Mobile Download Links"
    },
    tr: {
        lang: "tr",
        welcome: "Hoşgeldiniz",
        mealList: "Yemek Listesi",
        mustFaculty: "Fakülte (Zorunlu)",
        editProfile: "Profil Düzenle",
        canEdit: "Düzenleme yapabilirsiniz.",
        username: "Kullanıcı Adı",
        urUsername: "Kullanıcı adınız",
        mustDepartment: "Bölüm (Zorunlu)",
        cancel: "Vazgeç",
        save: "Kaydet",
        faculty: "Fakülte",
        department: "Bölüm",
        mood: "Mod",
        edit: "Düzenle",
        calendarString1: "fakültesinin programı bulunamadı.",
        calendarString2: "En kısa zamanda eklenecektir.",
        departmentSite1: "websitesi bulunamadı.",
        fillTheGaps: "Alanları doldurunuz.",
        start: "Başla",
        onboarding1Text: "Artık AYBÜ’nün de bir mobil uygulaması var.",
        onboarding2Text: "Bugün ne yiyeceğinizi tek tıkla öğrenin ve duygularınızı belirtin",
        onboarding3Text: "Yemeklere yorum yapabilme şansını yakalayın.",
        onboarding4Text: "En sevilen ve sevilmeyen yemekler hakkında bilgi sahibi olun.",
        onboarding1Title: "Merhaba",
        onboarding2Title: "Yemek listesi",
        onboarding3Title: "Yorum özelliği",
        onboarding4Title: "Trendler",
        noComment1: "Hiç yorum yok.",
        noComment2: "İlk yorum yapan sen ol!",
        error: "Hata",
        success: "Başarılı",
        registeredSuccess: "Giriş yapılıyor..",
        cantLogin: "Giriş yapılamadı. Lütfen tekrar deneyiniz",
        cantRegister: "Bu kullanıcı adı daha önce alınmış",
        writeComment: "Yorum yaz...",
        commentCouldntSend: "Yorumlar getirilemedi",
        anErrorOccured: "Bir hata oluştu",
        mealList: 'Yemek Listesi',
        successUpdate: "Profiliniz güncellendi.",
        trends: "TRENDLER",
        mostFavoriteDays: "En Çok Beğenilen Günler",
        mostUnfavoriteDays: "En Beğenilmeyen Günler",
        mostCommentDays: "En Çok Yorum Alan Günler",
        today: "Bugün",
        monday: "Pazartesi",
        tuesday: "Salı",
        wednesday: "Çarşamba",
        thursday: "Perşembe",
        friday: "Cuma",
        saturday: "Cumartesi",
        sunday: "Pazar",
        examSchedule: "Sınav Takvimi",
        syllabus: "Ders Programı",
        helpAYBU: "Bu belgeyi mail ile pdf formatında göndererek Aybü Mobil'e eklenmesinde yardımcı olabilirsiniz.",
        clickToSendMail: "Mail göndermek için tıklayınız.",
        sharedWithFriends: "Arkadaşlarınla paylaş!",
        skip: "Geç",
        selectDepartment: "Bölüm Seç",
        selectFaculty: "Fakülte Seçin",
        downloadLinks: "AYBÜ Mobil İndirme Linkleri"
    }
})